/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hv93IUIFmW5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu";

export default function spotify1() {
    return (
        <div className="flex min-h-screen w-full bg-background text-foreground">
            <aside className="hidden w-64 flex-col border-r bg-background p-4 lg:flex">
                <div className="flex items-center gap-2">
                    <AirplayIcon className="h-8 w-8 text-primary" />
                    <span className="text-2xl font-bold">Spotify</span>
                </div>
                <nav className="mt-8 flex flex-col gap-2">
                    <Link
                        href="#"
                        className="flex items-center gap-2 rounded-md px-3 py-2 text-lg font-medium transition-colors hover:bg-muted"
                        prefetch={false}
                    >
                        <HomeIcon className="h-6 w-6" />
                        Home
                    </Link>
                    <Link
                        href="#"
                        className="flex items-center gap-2 rounded-md px-3 py-2 text-lg font-medium transition-colors hover:bg-muted"
                        prefetch={false}
                    >
                        <SearchIcon className="h-6 w-6" />
                        Search
                    </Link>
                    <Link
                        href="#"
                        className="flex items-center gap-2 rounded-md px-3 py-2 text-lg font-medium transition-colors hover:bg-muted"
                        prefetch={false}
                    >
                        <LibraryIcon className="h-6 w-6" />
                        Your Library
                    </Link>
                </nav>
                <div className="mt-auto">
                    <h3 className="mb-2 text-lg font-medium">Playlists</h3>
                    <div className="flex flex-col gap-2">
                        <Link
                            href="#"
                            className="flex items-center gap-2 rounded-md px-3 py-2 text-lg font-medium transition-colors hover:bg-muted"
                            prefetch={false}
                        >
                            <PlusIcon className="h-6 w-6" />
                            Create Playlist
                        </Link>
                        <Link
                            href="#"
                            className="flex items-center gap-2 rounded-md px-3 py-2 text-lg font-medium transition-colors hover:bg-muted"
                            prefetch={false}
                        >
                            <HeartIcon className="h-6 w-6" />
                            Liked Songs
                        </Link>
                    </div>
                </div>
            </aside>
            <div className="flex flex-1 flex-col">
                <header className="sticky top-0 z-10 flex h-14 items-center justify-between border-b bg-background px-4 shadow-sm md:px-6">
                    <div className="flex items-center gap-4">
                        <Button variant="ghost" size="icon" className="lg:hidden">
                            <MenuIcon className="h-6 w-6" />
                            <span className="sr-only">Toggle sidebar</span>
                        </Button>
                        <div className="relative flex-1">
                            <SearchIcon className="absolute left-2.5 top-2.5 h-5 w-5 text-muted-foreground" />
                            <Input
                                type="search"
                                placeholder="Search"
                                className="w-full rounded-full bg-muted pl-8 pr-4 focus:bg-background"
                            />
                        </div>
                    </div>
                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon" className="overflow-hidden rounded-full">
                                <img
                                    src="/placeholder.svg"
                                    width={32}
                                    height={32}
                                    alt="User avatar"
                                    className="rounded-full"
                                    style={{ aspectRatio: "32/32", objectFit: "cover" }}
                                />
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                            <DropdownMenuLabel>My Account</DropdownMenuLabel>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem>Settings</DropdownMenuItem>
                            <DropdownMenuItem>Log Out</DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>
                </header>
                <main className="flex-1 overflow-auto p-4 md:p-6">
                    <div className="grid gap-6">
                        <div>
                            <h2 className="mb-4 text-2xl font-bold">Recently Played</h2>
                            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
                                {[...Array(12)].map((_, i) => (
                                    <div key={i} className="group">
                                        <Link href="#" className="relative block aspect-square overflow-hidden rounded-md" prefetch={false}>
                                            <img
                                                src="/placeholder.svg"
                                                alt={`Album ${i + 1}`}
                                                width="200"
                                                height="200"
                                                className="h-full w-full object-cover transition-all group-hover:scale-110"
                                                style={{ aspectRatio: "200/200", objectFit: "cover" }}
                                            />
                                            <div className="absolute inset-0 flex items-center justify-center bg-black/50 opacity-0 transition-opacity group-hover:opacity-100">
                                                <Button variant="ghost" size="icon" className="text-white">
                                                    <PlayIcon className="h-8 w-8" />
                                                    <span className="sr-only">Play</span>
                                                </Button>
                                            </div>
                                        </Link>
                                        <div className="mt-2 truncate">
                                            <h3 className="text-lg font-medium">Album {i + 1}</h3>
                                            <p className="text-sm text-muted-foreground">Artist {i + 1}</p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                        <div>
                            <h2 className="mb-4 text-2xl font-bold">Your Playlists</h2>
                            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
                                {[...Array(12)].map((_, i) => (
                                    <div key={i} className="group">
                                        <Link href="#" className="relative block aspect-square overflow-hidden rounded-md" prefetch={false}>
                                            <img
                                                src="/placeholder.svg"
                                                alt={`Playlist ${i + 1}`}
                                                width="200"
                                                height="200"
                                                className="h-full w-full object-cover transition-all group-hover:scale-110"
                                                style={{ aspectRatio: "200/200", objectFit: "cover" }}
                                            />
                                            <div className="absolute inset-0 flex items-center justify-center bg-black/50 opacity-0 transition-opacity group-hover:opacity-100">
                                                <Button variant="ghost" size="icon" className="text-white">
                                                    <PlayIcon className="h-8 w-8" />
                                                    <span className="sr-only">Play</span>
                                                </Button>
                                            </div>
                                        </Link>
                                        <div className="mt-2 truncate">
                                            <h3 className="text-lg font-medium">Playlist {i + 1}</h3>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                        <div>
                            <h2 className="mb-4 text-2xl font-bold">Albums</h2>
                            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
                                {[...Array(12)].map((_, i) => (
                                    <div key={i} className="group">
                                        <Link href="#" className="relative block aspect-square overflow-hidden rounded-md" prefetch={false}>
                                            <img
                                                src="/placeholder.svg"
                                                alt={`Album ${i + 1}`}
                                                width="200"
                                                height="200"
                                                className="h-full w-full object-cover transition-all group-hover:scale-110"
                                                style={{ aspectRatio: "200/200", objectFit: "cover" }}
                                            />
                                            <div className="absolute inset-0 flex items-center justify-center bg-black/50 opacity-0 transition-opacity group-hover:opacity-100">
                                                <Button variant="ghost" size="icon" className="text-white">
                                                    <PlayIcon className="h-8 w-8" />
                                                    <span className="sr-only">Play</span>
                                                </Button>
                                            </div>
                                        </Link>
                                        <div className="mt-2 truncate">
                                            <h3 className="text-lg font-medium">Album {i + 1}</h3>
                                            <p className="text-sm text-muted-foreground">Artist {i + 1}</p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
    );
}

function AirplayIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1" />
            <path d="m12 15 5 6H7Z" />
        </svg>
    );
}


function HeartIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
        </svg>
    );
}


function HomeIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
            <polyline points="9 22 9 12 15 12 15 22" />
        </svg>
    );
}


function LibraryIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m16 6 4 14" />
            <path d="M12 6v14" />
            <path d="M8 8v12" />
            <path d="M4 4v16" />
        </svg>
    );
}


function MenuIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <line x1="4" x2="20" y1="12" y2="12" />
            <line x1="4" x2="20" y1="6" y2="6" />
            <line x1="4" x2="20" y1="18" y2="18" />
        </svg>
    );
}


function PlayIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <polygon points="6 3 20 12 6 21 6 3" />
        </svg>
    );
}


function PlusIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M5 12h14" />
            <path d="M12 5v14" />
        </svg>
    );
}


function SearchIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="11" cy="11" r="8" />
            <path d="m21 21-4.3-4.3" />
        </svg>
    );
}
