/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SXi8qWX27AT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Separator } from "@/components/ui/separator";

export default function youtube1() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-background border-b flex items-center justify-between px-4 sm:px-6 h-14 sm:h-16">
        <div className="flex items-center gap-4">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <YoutubeIcon className="w-8 h-8 text-red-500" />
            <span className="text-lg font-semibold">YouTube</span>
          </Link>
          <div className="relative flex-1 max-w-md">
            <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
            <Input
              type="search"
              placeholder="Search"
              className="w-full rounded-full bg-muted pl-10 pr-4 py-2 text-sm"
            />
          </div>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" className="rounded-full">
            <UploadIcon className="w-6 h-6" />
            <span className="sr-only">Upload</span>
          </Button>
          <Button variant="ghost" size="icon" className="rounded-full">
            <BellIcon className="w-6 h-6" />
            <span className="sr-only">Notifications</span>
          </Button>
          <Avatar className="w-8 h-8 border">
            <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
            <AvatarFallback>AC</AvatarFallback>
          </Avatar>
        </div>
      </header>
      <div className="flex flex-1">
        <aside className="bg-muted/40 border-r hidden sm:block w-64 p-4">
          <nav className="grid gap-2">
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <HomeIcon className="w-5 h-5" />
              <span>Home</span>
            </Link>
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <CompassIcon className="w-5 h-5" />
              <span>Explore</span>
            </Link>
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <ShoppingCartIcon className="w-5 h-5" />
              <span>Subscriptions</span>
            </Link>
            <Separator className="my-2" />
            <div className="px-3 text-xs font-medium text-muted-foreground">CATEGORIES</div>
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <FilmIcon className="w-5 h-5" />
              <span>Films</span>
            </Link>
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <Music2Icon className="w-5 h-5" />
              <span>Music</span>
            </Link>
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <GamepadIcon className="w-5 h-5" />
              <span>Gaming</span>
            </Link>
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <NewspaperIcon className="w-5 h-5" />
              <span>News</span>
            </Link>
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <ClubIcon className="w-5 h-5" />
              <span>Sports</span>
            </Link>
            <Separator className="my-2" />
            <div className="px-3 text-xs font-medium text-muted-foreground">SUBSCRIPTIONS</div>
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <Avatar className="w-6 h-6 border">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>AC</AvatarFallback>
              </Avatar>
              <span>Acme Inc</span>
            </Link>
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <Avatar className="w-6 h-6 border">
                <AvatarImage src="/placeholder-user.jpg" alt="@jaredpalmer" />
                <AvatarFallback>JP</AvatarFallback>
              </Avatar>
              <span>Jared Palmer</span>
            </Link>
            <Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2 hover:bg-muted" prefetch={false}>
              <Avatar className="w-6 h-6 border">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <span>Shadcn</span>
            </Link>
          </nav>
        </aside>
        <main className="flex-1 p-4 sm:p-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-6">
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Thumbnail"
                width={320}
                height={180}
                className="w-full aspect-video rounded-lg object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute inset-0 flex flex-col justify-end p-4">
                <h3 className="text-lg font-medium text-white line-clamp-2 group-hover:underline">
                  Vercel Ship Keynote: Introducing the frontend cloud
                </h3>
                <div className="flex items-center gap-2 mt-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-white/80 line-clamp-1">Vercel</span>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Thumbnail"
                width={320}
                height={180}
                className="w-full aspect-video rounded-lg object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute inset-0 flex flex-col justify-end p-4">
                <h3 className="text-lg font-medium text-white line-clamp-2 group-hover:underline">
                  Introducing v0: Generative UI
                </h3>
                <div className="flex items-center gap-2 mt-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-white/80 line-clamp-1">Vercel</span>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Thumbnail"
                width={320}
                height={180}
                className="w-full aspect-video rounded-lg object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute inset-0 flex flex-col justify-end p-4">
                <h3 className="text-lg font-medium text-white line-clamp-2 group-hover:underline">
                  Using Vercel KV with Svelte
                </h3>
                <div className="flex items-center gap-2 mt-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@lee-robinson" />
                    <AvatarFallback>LR</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-white/80 line-clamp-1">Lee Robinson</span>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Thumbnail"
                width={320}
                height={180}
                className="w-full aspect-video rounded-lg object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute inset-0 flex flex-col justify-end p-4">
                <h3 className="text-lg font-medium text-white line-clamp-2 group-hover:underline">
                  Loading UI with Next.js 13
                </h3>
                <div className="flex items-center gap-2 mt-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@delba" />
                    <AvatarFallback>DB</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-white/80 line-clamp-1">Delba</span>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Thumbnail"
                width={320}
                height={180}
                className="w-full aspect-video rounded-lg object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute inset-0 flex flex-col justify-end p-4">
                <h3 className="text-lg font-medium text-white line-clamp-2 group-hover:underline">
                  Introducing the frontend cloud
                </h3>
                <div className="flex items-center gap-2 mt-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-white/80 line-clamp-1">Vercel</span>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Thumbnail"
                width={320}
                height={180}
                className="w-full aspect-video rounded-lg object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute inset-0 flex flex-col justify-end p-4">
                <h3 className="text-lg font-medium text-white line-clamp-2 group-hover:underline">
                  Vercel Ship Keynote: Introducing the frontend cloud
                </h3>
                <div className="flex items-center gap-2 mt-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-white/80 line-clamp-1">Vercel</span>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Thumbnail"
                width={320}
                height={180}
                className="w-full aspect-video rounded-lg object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute inset-0 flex flex-col justify-end p-4">
                <h3 className="text-lg font-medium text-white line-clamp-2 group-hover:underline">
                  Introducing v0: Generative UI
                </h3>
                <div className="flex items-center gap-2 mt-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-white/80 line-clamp-1">Vercel</span>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Thumbnail"
                width={320}
                height={180}
                className="w-full aspect-video rounded-lg object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute inset-0 flex flex-col justify-end p-4">
                <h3 className="text-lg font-medium text-white line-clamp-2 group-hover:underline">
                  Using Vercel KV with Svelte
                </h3>
                <div className="flex items-center gap-2 mt-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@lee-robinson" />
                    <AvatarFallback>LR</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-white/80 line-clamp-1">Lee Robinson</span>
                </div>
              </div>
            </Link>
          </div>
        </main>
      </div>
      <footer className="bg-muted/40 border-t p-4 sm:p-6 flex items-center justify-between">
        <div className="text-sm text-muted-foreground">&copy; 2024 YouTube. All rights reserved.</div>
        <nav className="flex items-center gap-4">
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Terms
          </Link>
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Privacy
          </Link>
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Policy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  );
}


function ClubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.28 9.05a5.5 5.5 0 1 0-10.56 0A5.5 5.5 0 1 0 12 17.66a5.5 5.5 0 1 0 5.28-8.6Z" />
      <path d="M12 17.66L12 22" />
    </svg>
  );
}


function CompassIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />
      <circle cx="12" cy="12" r="10" />
    </svg>
  );
}


function FilmIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M7 3v18" />
      <path d="M3 7.5h4" />
      <path d="M3 12h18" />
      <path d="M3 16.5h4" />
      <path d="M17 3v18" />
      <path d="M17 7.5h4" />
      <path d="M17 16.5h4" />
    </svg>
  );
}


function GamepadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="6" x2="10" y1="12" y2="12" />
      <line x1="8" x2="8" y1="10" y2="14" />
      <line x1="15" x2="15.01" y1="13" y2="13" />
      <line x1="18" x2="18.01" y1="11" y2="11" />
      <rect width="20" height="12" x="2" y="6" rx="2" />
    </svg>
  );
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}


function Music2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="18" r="4" />
      <path d="M12 18V2l7 4" />
    </svg>
  );
}


function NewspaperIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 22h16a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16a2 2 0 0 1-2 2Zm0 0a2 2 0 0 1-2-2v-9c0-1.1.9-2 2-2h2" />
      <path d="M18 14h-8" />
      <path d="M15 18h-5" />
      <path d="M10 6h8v4h-8V6Z" />
    </svg>
  );
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  );
}


function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  );
}


function YoutubeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  );
}
