/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/h1QYo2oMDbs
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion"

export function timeline() {
  return (
    <div className="p-6 sm:p-10">
      <div className="after:absolute after:inset-y-0 after:w-px after:bg-muted-foreground/20 relative pl-6 after:left-0 grid gap-10">
        <div className="grid gap-1 text-sm relative">
          <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
          <Card>
            <CardHeader>
              <CardTitle>Project Kickoff</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4">
              <p>
                The project kickoff meeting is scheduled for next Monday at 10am. Please make sure to attend and come
                prepared with any initial questions or concerns.
              </p>
              <Accordion type="single" collapsible>
                <AccordionItem value="item-1">
                  <AccordionTrigger>What is the purpose of the kickoff meeting?</AccordionTrigger>
                  <AccordionContent>
                    The kickoff meeting is an opportunity for the entire project team to get on the same page. We'll
                    review the project scope, timeline, and responsibilities.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-2">
                  <AccordionTrigger>Who should attend the kickoff meeting?</AccordionTrigger>
                  <AccordionContent>
                    The kickoff meeting should be attended by the project manager, key stakeholders, and any team
                    members who will be directly involved in the project.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-3">
                  <AccordionTrigger>What should I bring to the kickoff meeting?</AccordionTrigger>
                  <AccordionContent>
                    Please bring any relevant project documents, your calendar, and a list of questions or concerns
                    you'd like to discuss.
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-1 text-sm relative">
          <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
          <Card>
            <CardHeader>
              <CardTitle>Design Review</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4">
              <p>
                The design review meeting is scheduled for next Friday at 2pm. Please come prepared to provide feedback
                on the initial design concepts.
              </p>
              <Accordion type="single" collapsible>
                <AccordionItem value="item-1">
                  <AccordionTrigger>What will be covered in the design review?</AccordionTrigger>
                  <AccordionContent>
                    We'll be reviewing the initial wireframes, mockups, and prototypes to ensure the design aligns with
                    the project requirements.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-2">
                  <AccordionTrigger>Who should attend the design review?</AccordionTrigger>
                  <AccordionContent>
                    The design review should be attended by the project manager, key stakeholders, and any team members
                    who will be responsible for implementing the design.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-3">
                  <AccordionTrigger>What should I bring to the design review?</AccordionTrigger>
                  <AccordionContent>
                    Please bring any feedback, comments, or questions you have about the design concepts. We'll be
                    discussing them in detail during the meeting.
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-1 text-sm relative">
          <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
          <Card>
            <CardHeader>
              <CardTitle>Development Sprint Review</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4">
              <p>
                The development sprint review is scheduled for next Wednesday at 3pm. We'll be reviewing the progress
                made during the current sprint and planning for the next one.
              </p>
              <Accordion type="single" collapsible>
                <AccordionItem value="item-1">
                  <AccordionTrigger>What is the purpose of the sprint review?</AccordionTrigger>
                  <AccordionContent>
                    The sprint review is an opportunity for the team to demonstrate the work completed during the
                    current sprint, get feedback from stakeholders, and plan for the next sprint.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-2">
                  <AccordionTrigger>Who should attend the sprint review?</AccordionTrigger>
                  <AccordionContent>
                    The sprint review should be attended by the project manager, the development team, and any key
                    stakeholders who need to provide feedback or approve the work.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-3">
                  <AccordionTrigger>What should I bring to the sprint review?</AccordionTrigger>
                  <AccordionContent>
                    Please come prepared to demonstrate the work you've completed during the current sprint. You may
                    also want to bring any questions or concerns you have about the project roadmap or next steps.
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
