/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/beo3ZOZqo1T
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Separator } from "@/components/ui/separator"

export default function youtube2() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-background border-b shadow-sm sticky top-0 z-40">
        <div className="container px-4 md:px-6 flex items-center h-14 gap-4">
          <Link href="#" className="flex items-center gap-2 font-semibold" prefetch={false}>
            <YoutubeIcon className="w-8 h-8 text-red-500" />
            <span className="hidden sm:inline">YouTube</span>
          </Link>
          <div className="flex-1 max-w-md">
            <form>
              <Input type="search" placeholder="Search" className="w-full rounded-full bg-muted pr-10" />
            </form>
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="rounded-full">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                  <AvatarFallback>AC</AvatarFallback>
                </Avatar>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <div className="flex-1 container px-4 md:px-6 grid grid-cols-1 md:grid-cols-[240px_1fr] gap-8 py-8">
        <nav className="hidden md:block">
          <div className="space-y-2">
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}
            >
              <HomeIcon className="w-5 h-5" />
              Home
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}
            >
              <CompassIcon className="w-5 h-5" />
              Explore
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}
            >
              <ShoppingCartIcon className="w-5 h-5" />
              Subscriptions
            </Link>
            <Separator />
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}
            >
              <LibraryIcon className="w-5 h-5" />
              Library
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}
            >
              <CalendarIcon className="w-5 h-5" />
              History
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}
            >
              <ClockIcon className="w-5 h-5" />
              Watch Later
            </Link>
            <Link
              href="#"
              className="flex items-center gap-3 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}
            >
              <ThumbsUpIcon className="w-5 h-5" />
              Liked Videos
            </Link>
          </div>
        </nav>
        <main>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Video Thumbnail"
                width={320}
                height={180}
                className="w-full rounded-lg aspect-video object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute bottom-2 left-2 bg-background/80 px-2 py-1 rounded-md text-sm">
                <div className="font-medium line-clamp-1">Vercel Ship Keynote: Introducing the frontend cloud</div>
                <div className="flex items-center gap-1 text-muted-foreground">
                  <div className="line-clamp-1">Vercel</div>
                  <div className="h-1 w-1 rounded-full bg-muted-foreground" />
                  <div className="line-clamp-1">1.2M views</div>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Video Thumbnail"
                width={320}
                height={180}
                className="w-full rounded-lg aspect-video object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute bottom-2 left-2 bg-background/80 px-2 py-1 rounded-md text-sm">
                <div className="font-medium line-clamp-1">Introducing v0: Generative UI</div>
                <div className="flex items-center gap-1 text-muted-foreground">
                  <div className="line-clamp-1">Vercel</div>
                  <div className="h-1 w-1 rounded-full bg-muted-foreground" />
                  <div className="line-clamp-1">300K views</div>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Video Thumbnail"
                width={320}
                height={180}
                className="w-full rounded-lg aspect-video object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute bottom-2 left-2 bg-background/80 px-2 py-1 rounded-md text-sm">
                <div className="font-medium line-clamp-1">Using Vercel KV with Svelte</div>
                <div className="flex items-center gap-1 text-muted-foreground">
                  <div className="line-clamp-1">Lee Robinson</div>
                  <div className="h-1 w-1 rounded-full bg-muted-foreground" />
                  <div className="line-clamp-1">21K views</div>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Video Thumbnail"
                width={320}
                height={180}
                className="w-full rounded-lg aspect-video object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute bottom-2 left-2 bg-background/80 px-2 py-1 rounded-md text-sm">
                <div className="font-medium line-clamp-1">Loading UI with Next.js 13</div>
                <div className="flex items-center gap-1 text-muted-foreground">
                  <div className="line-clamp-1">Delba</div>
                  <div className="h-1 w-1 rounded-full bg-muted-foreground" />
                  <div className="line-clamp-1">12K views</div>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Video Thumbnail"
                width={320}
                height={180}
                className="w-full rounded-lg aspect-video object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute bottom-2 left-2 bg-background/80 px-2 py-1 rounded-md text-sm">
                <div className="font-medium line-clamp-1">Introducing the frontend cloud</div>
                <div className="flex items-center gap-1 text-muted-foreground">
                  <div className="line-clamp-1">Vercel</div>
                  <div className="h-1 w-1 rounded-full bg-muted-foreground" />
                  <div className="line-clamp-1">1.2M views</div>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Video Thumbnail"
                width={320}
                height={180}
                className="w-full rounded-lg aspect-video object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute bottom-2 left-2 bg-background/80 px-2 py-1 rounded-md text-sm">
                <div className="font-medium line-clamp-1">Vercel Ship Keynote: Introducing the frontend cloud</div>
                <div className="flex items-center gap-1 text-muted-foreground">
                  <div className="line-clamp-1">Vercel</div>
                  <div className="h-1 w-1 rounded-full bg-muted-foreground" />
                  <div className="line-clamp-1">1.2M views</div>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Video Thumbnail"
                width={320}
                height={180}
                className="w-full rounded-lg aspect-video object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute bottom-2 left-2 bg-background/80 px-2 py-1 rounded-md text-sm">
                <div className="font-medium line-clamp-1">Introducing v0: Generative UI</div>
                <div className="flex items-center gap-1 text-muted-foreground">
                  <div className="line-clamp-1">Vercel</div>
                  <div className="h-1 w-1 rounded-full bg-muted-foreground" />
                  <div className="line-clamp-1">300K views</div>
                </div>
              </div>
            </Link>
            <Link href="#" className="group relative" prefetch={false}>
              <img
                src="/placeholder.svg"
                alt="Video Thumbnail"
                width={320}
                height={180}
                className="w-full rounded-lg aspect-video object-cover group-hover:opacity-80 transition-opacity"
              />
              <div className="absolute bottom-2 left-2 bg-background/80 px-2 py-1 rounded-md text-sm">
                <div className="font-medium line-clamp-1">Using Vercel KV with Svelte</div>
                <div className="flex items-center gap-1 text-muted-foreground">
                  <div className="line-clamp-1">Lee Robinson</div>
                  <div className="h-1 w-1 rounded-full bg-muted-foreground" />
                  <div className="line-clamp-1">21K views</div>
                </div>
              </div>
            </Link>
          </div>
        </main>
      </div>
    </div>
  )
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function CompassIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function LibraryIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 6 4 14" />
      <path d="M12 6v14" />
      <path d="M8 8v12" />
      <path d="M4 4v16" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function ThumbsUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}


function YoutubeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}
